console.log(typeof parseInt("1.2582"))
console.log(parseInt("0.2582"))
console.log(parseFloat("1.2582"))
console.log(parseFloat(1))
console.log(typeof parseInt("jhguyg"))
console.log( parseInt("jhguyg"))